version: "3.9"

services:
  backend:
    build:
      context: ./backend-cc
      dockerfile: Dockerfile
    container_name: backend-cc
    ports:
      - "3004:3004"
    env_file:
      - ./backend-cc/.env
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./frond-cc
      dockerfile: Dockerfile
    container_name: frond-cc
    ports:
      - "82:80"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
