name: CI/CD Full Stack (Frontend + Backend) on AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Clonar el repositorio localmente en Actions
      - name: Checkout code
        uses: actions/checkout@v4

      # 2Ô∏è‚É£ Login en Docker Hub
      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3Ô∏è‚É£ Build Backend
      - name: Build Backend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-cc:latest ./backend-cc

      # 4Ô∏è‚É£ Build Frontend
      - name: Build Frontend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frond-cc:latest ./frond-cc

      # 5Ô∏è‚É£ Push Backend
      - name: Push Backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend-cc:latest

      # 6Ô∏è‚É£ Push Frontend
      - name: Push Frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frond-cc:latest

      # 7Ô∏è‚É£ Deploy autom√°tico en EC2
      - name: Deploy on AWS EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }} # por ejemplo 'ubuntu'
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "üöÄ Desplegando aplicaci√≥n CenterDivisa en EC2..."

            # Crear carpeta si no existe y clonar repo
            if [ ! -d "/home/${{ secrets.SERVER_USER }}/centerdivisa" ]; then
              echo "Repositorio no existe, clonando..."
              cd /home/${{ secrets.SERVER_USER }}
              git clone https://github.com/ElGeras90/centerdivisa.git
            else
              echo "Repositorio ya existe, actualizando..."
              cd /home/${{ secrets.SERVER_USER }}/centerdivisa
              git reset --hard
              git pull origin main
            fi

            # Login a Docker Hub
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            # Bajar las √∫ltimas im√°genes
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend-cc:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/frond-cc:latest

            # Asegurarse que docker-compose use las im√°genes del Hub
            sed -i "s|build:.*backend-cc.*|image: ${{ secrets.DOCKER_USERNAME }}/backend-cc:latest|" docker-compose.yml
            sed -i '/context:/,+1d' docker-compose.yml
            sed -i "s|build:.*frond-cc.*|image: ${{ secrets.DOCKER_USERNAME }}/frond-cc:latest|" docker-compose.yml

            # Levantar contenedores
            docker compose down
            docker compose up -d --force-recreate

            echo "‚úÖ Despliegue completado correctamente"
